export const Types = {
  GET_TICKETS_REQUEST: 'GET_TICKETS_REQUEST',
  GET_TICKETS_SUCCESS: 'GET_TICKETS_SUCCESS',

  GET_SINGLE_TICKET_REQUEST: 'GET_SINGLE_TICKET_REQUEST',
  GET_SINGLE_TICKET_SUCCESS: 'GET_SINGLE_TICKET_SUCCESS',
  UNSET_TICKET_DETAIL: 'UNSET_TICKET_DETAIL',

  CREATE_TICKET_REQUEST: 'CREATE_TICKET_REQUEST',
  CREATE_TICKET_SUCCESS: 'CREATE_TICKET_SUCCESS',

  COMPLETE_TICKET_REQUEST: 'COMPLETE_TICKET_REQUEST',
  COMPLETE_TICKET_SUCCESS: 'COMPLETE_TICKET_SUCCESS',

  INCOMPLETE_TICKET_REQUEST: 'INCOMPLETE_TICKET_REQUEST',
  INCOMPLETE_TICKET_SUCCESS: 'INCOMPLETE_TICKET_SUCCESS',

  ASSIGN_TICKET_REQUEST: 'ASSIGN_TICKET_REQUEST',
  ASSIGN_TICKET_SUCCESS: 'ASSIGN_TICKET_SUCCESS',

  UNASSIGN_TICKET_REQUEST: 'UNASSIGN_TICKET_REQUEST',
  UNASSIGN_TICKET_SUCCESS: 'UNASSIGN_TICKET_SUCCESS',

  GET_USERS_REQUEST: 'GET_USERS_REQUEST',
  GET_USERS_SUCCESS: 'GET_USERS_SUCCESS',
};
